#
# Defines the Role Based Access Control resources that are needed by the Controller in order to access the Ingress resources
#
apiVersion: v1
kind: Namespace
metadata:
  name: ns-kkfi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-kkfi
  namespace: ns-kkfi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cr-ingress-get-list-watch
rules:
  - apiGroups: ["extensions/v1beta1"]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "kkfi:cr-ingress-get-list-watch"
  namespace: ns-kkfi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cr-ingress-get-list-watch
subjects:
  - kind: ServiceAccount
    name: sa-kkfi
    namespace: ns-kkfi
