apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "k8s-kong-federated-ingress:ingress-resource-get-watch-list"
subjects:
  - kind: ServiceAccount
    name: k8s-kong-federated-ingress
    namespace: default
roleRef:
  kind: ClusterRole
  name: ingress-resource-get-watch-list
  apiGroup: rbac.authorization.k8s.io
