apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-resource-get-watch-list
rules:
  - apiGroups: [""]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]