apiVersion: v1
kind: Secret
metadata:
  name: k8s-kong-federated-ingress-secret
  annotations:
    kubernetes.io/service-account.name: k8s-kong-federated-ingress
type: kubernetes.io/service-account-token
