apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-kong-federated-ingress
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ingress-resource-get-watch-list
rules:
  - apiGroups: [""]
    resources: ["ingresses"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "k8s-kong-federated-ingress:ingress-resource-get-watch-list"
subjects:
  - kind: ServiceAccount
    name: k8s-kong-federated-ingress
    namespace: default
roleRef:
  kind: ClusterRole
  name: ingress-resource-get-watch-list
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: k8s-kong-federated-ingress-secret
  annotations:
    kubernetes.io/service-account.name: k8s-kong-federated-ingress
type: kubernetes.io/service-account-token

